# Generated by Django 2.2.19 on 2021-03-19 05:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'.         Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='contact_phone', to='contacts.Contacts')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
