# Generated by Django 2.2.19 on 2021-03-09 05:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterField(
            model_name='phones',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='contact_phone', to='phones.Contacts'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'.         Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
