# Generated by Django 2.2.19 on 2021-03-11 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210309_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='contact_phone', to='contacts.Contacts'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
