# Generated by Django 2.2.19 on 2021-03-18 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20210318_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'.         Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
